import type { CatalogSong, EraId } from "./types";
import { guessMatches } from "./guess";

type Row = [title: string, artist: string, year: number, german?: 1];

const ROWS: Row[] = [
  ["Rock Around the Clock", "Bill Haley & His Comets", 1954],
  ["Hound Dog", "Elvis Presley", 1956],
  ["Jailhouse Rock", "Elvis Presley", 1957],
  ["Johnny B. Goode", "Chuck Berry", 1958],
  ["What'd I Say", "Ray Charles", 1959],
  ["The Twist", "Chubby Checker", 1960],
  ["Stand by Me", "Ben E. King", 1961],
  ["I Want to Hold Your Hand", "The Beatles", 1963],
  ["She Loves You", "The Beatles", 1963],
  ["(I Can't Get No) Satisfaction", "The Rolling Stones", 1965],
  ["Help!", "The Beatles", 1965],
  ["My Generation", "The Who", 1965],
  ["Good Vibrations", "The Beach Boys", 1966],
  ["Paint It, Black", "The Rolling Stones", 1966],
  ["Respect", "Aretha Franklin", 1967],
  ["Light My Fire", "The Doors", 1967],
  ["A Whiter Shade of Pale", "Procol Harum", 1967],
  ["Hey Jude", "The Beatles", 1968],
  ["All Along the Watchtower", "Jimi Hendrix", 1968],
  ["I Heard It Through the Grapevine", "Marvin Gaye", 1968],
  ["Whole Lotta Love", "Led Zeppelin", 1969],
  ["Come Together", "The Beatles", 1969],
  ["Let It Be", "The Beatles", 1970],
  ["Your Song", "Elton John", 1970],
  ["Imagine", "John Lennon", 1971],
  ["Stairway to Heaven", "Led Zeppelin", 1971],
  ["Superstition", "Stevie Wonder", 1972],
  ["Smoke on the Water", "Deep Purple", 1972],
  ["Angie", "The Rolling Stones", 1973],
  ["Autobahn", "Kraftwerk", 1974, 1],
  ["Bohemian Rhapsody", "Queen", 1975],
  ["Wish You Were Here", "Pink Floyd", 1975],
  ["Dancing Queen", "ABBA", 1976],
  ["Hotel California", "Eagles", 1977],
  ["Stayin' Alive", "Bee Gees", 1977],
  ["We Are the Champions", "Queen", 1977],
  ["Y.M.C.A.", "Village People", 1978],
  ["Heart of Glass", "Blondie", 1978],
  ["Another Brick in the Wall, Pt. 2", "Pink Floyd", 1979],
  ["Don't Stop Believin'", "Journey", 1981],
  ["In the Air Tonight", "Phil Collins", 1981],
  ["Tainted Love", "Soft Cell", 1981],
  ["Da Da Da", "Trio", 1982, 1],
  ["Billie Jean", "Michael Jackson", 1983],
  ["Every Breath You Take", "The Police", 1983],
  ["99 Luftballons", "Nena", 1983, 1],
  ["Sonderzug nach Pankow", "Udo Lindenberg", 1983, 1],
  ["Relax", "Frankie Goes to Hollywood", 1983],
  ["Like a Virgin", "Madonna", 1984],
  ["When Doves Cry", "Prince", 1984],
  ["Forever Young", "Alphaville", 1984, 1],
  ["Männer", "Herbert Grönemeyer", 1984, 1],
  ["Take On Me", "a-ha", 1985],
  ["Rock Me Amadeus", "Falco", 1985, 1],
  ["You're My Heart, You're My Soul", "Modern Talking", 1985, 1],
  ["Summer of '69", "Bryan Adams", 1985],
  ["Livin' on a Prayer", "Bon Jovi", 1986],
  ["The Final Countdown", "Europe", 1986],
  ["Walk Like an Egyptian", "The Bangles", 1986],
  ["Sweet Child o' Mine", "Guns N' Roses", 1987],
  ["I Wanna Dance with Somebody", "Whitney Houston", 1987],
  ["Never Gonna Give You Up", "Rick Astley", 1987],
  ["Freiheit", "Westernhagen", 1987, 1],
  ["With or Without You", "U2", 1987],
  ["Fast Car", "Tracy Chapman", 1988],
  ["Hier kommt Alex", "Die Toten Hosen", 1988, 1],
  ["Like a Prayer", "Madonna", 1989],
  ["Wind of Change", "Scorpions", 1990, 1],
  ["Nothing Compares 2 U", "Sinéad O'Connor", 1990],
  ["The Power", "Snap!", 1990, 1],
  ["Smells Like Teen Spirit", "Nirvana", 1991],
  ["Black or White", "Michael Jackson", 1991],
  ["I Will Always Love You", "Whitney Houston", 1992],
  ["Under the Bridge", "Red Hot Chili Peppers", 1992],
  ["Killing in the Name", "Rage Against the Machine", 1992],
  ["What's Up?", "4 Non Blondes", 1993],
  ["Mr. Vain", "Culture Beat", 1993, 1],
  ["Die da!?", "Die Fantastischen Vier", 1993, 1],
  ["Linger", "The Cranberries", 1993],
  ["Zombie", "The Cranberries", 1994],
  ["Wonderwall", "Oasis", 1995],
  ["Gangsta's Paradise", "Coolio", 1995],
  ["You Oughta Know", "Alanis Morissette", 1995],
  ["Abenteuerland", "Pur", 1995, 1],
  ["Wannabe", "Spice Girls", 1996],
  ["Macarena", "Los Del Rio", 1996],
  ["Bitter Sweet Symphony", "The Verve", 1997],
  ["MMMBop", "Hanson", 1997],
  ["Du Hast", "Rammstein", 1997, 1],
  ["Believe", "Cher", 1998],
  ["...Baby One More Time", "Britney Spears", 1998],
  ["How Much Is the Fish?", "Scooter", 1998, 1],
  ["My Heart Will Go On", "Celine Dion", 1998],
  ["Californication", "Red Hot Chili Peppers", 1999],
  ["I Want It That Way", "Backstreet Boys", 1999],
  ["Smooth", "Santana", 1999],
  ["The Real Slim Shady", "Eminem", 2000],
  ["Yellow", "Coldplay", 2000],
  ["Bye Bye Bye", "NSYNC", 2000],
  ["Daylight in Your Eyes", "No Angels", 2001, 1],
  ["Fallin'", "Alicia Keys", 2001],
  ["Can't Get You Out of My Head", "Kylie Minogue", 2001],
  ["Whenever, Wherever", "Shakira", 2001],
  ["Lose Yourself", "Eminem", 2002],
  ["The Scientist", "Coldplay", 2002],
  ["A Thousand Miles", "Vanessa Carlton", 2002],
  ["Hey Ya!", "OutKast", 2003],
  ["Crazy in Love", "Beyoncé", 2003],
  ["In da Club", "50 Cent", 2003],
  ["Yeah!", "Usher", 2004],
  ["This Love", "Maroon 5", 2004],
  ["Perfekte Welle", "Juli", 2004, 1],
  ["Boulevard of Broken Dreams",  "Green Day", 2004],
  ["Feel Good Inc.", "Gorillaz", 2005],
  ["You're Beautiful", "James Blunt", 2005],
  ["Gold Digger", "Kanye West", 2005],
  ["Durch den Monsun", "Tokio Hotel", 2005, 1],
  ["Nur ein Wort", "Wir sind Helden", 2005, 1],
  ["Crazy", "Gnarls Barkley", 2006],
  ["Hips Don't Lie", "Shakira", 2006],
  ["Das Beste", "Silbermond", 2006, 1],
  ["Umbrella", "Rihanna", 2007],
  ["Rehab", "Amy Winehouse", 2007],
  ["Hamma!", "Culcha Candela", 2007, 1],
  ["Vom selben Stern", "Ich + Ich", 2007, 1],
  ["Viva la Vida", "Coldplay", 2008],
  ["Poker Face", "Lady Gaga", 2008],
  ["I Kissed a Girl", "Katy Perry", 2008],
  ["Haus am See", "Peter Fox", 2008, 1],
  ["I Gotta Feeling", "The Black Eyed Peas", 2009],
  ["Bad Romance", "Lady Gaga", 2009],
  ["Use Somebody", "Kings of Leon", 2008],
  ["Rolling in the Deep", "Adele", 2010],
  ["Satellite", "Lena", 2010, 1],
  ["Geboren um zu leben", "Unheilig", 2010, 1],
  ["Just the Way You Are", "Bruno Mars", 2010],
  ["Party Rock Anthem", "LMFAO", 2011],
  ["Somebody That I Used to Know", "Gotye", 2011],
  ["Rolling in the Deep", "Adele", 2010],
  ["Easy", "Cro", 2011, 1],
  ["Call Me Maybe", "Carly Rae Jepsen", 2011],
  ["We Are Young", "fun.", 2011],
  ["Gangnam Style", "PSY", 2012],
  ["Somebody That I Used to Know", "Gotye", 2011],
  ["Diamonds", "Rihanna", 2012],
  ["Locked Out of Heaven", "Bruno Mars", 2012],
  ["Get Lucky", "Daft Punk", 2013],
  ["Happy", "Pharrell Williams", 2013],
  ["Stolen Dance", "Milky Chance", 2013, 1],
  ["Atemlos durch die Nacht", "Helene Fischer", 2013, 1],
  ["Willst du", "Alligatoah", 2013, 1],
  ["All of Me", "John Legend", 2013],
  ["Uptown Funk", "Mark Ronson", 2014],
  ["Shake It Off", "Taylor Swift", 2014],
  ["Auf uns", "Andreas Bourani", 2014, 1],
  ["Chandelier", "Sia", 2014],
  ["Hello", "Adele", 2015],
  ["Sorry", "Justin Bieber", 2015],
  ["See You Again", "Wiz Khalifa", 2015],
  ["Lieblingsmensch", "Namika", 2015, 1],
  ["Chöre", "Mark Forster", 2015, 1],
  ["One Dance", "Drake", 2016],
  ["Cheap Thrills", "Sia", 2016],
  ["Can't Stop the Feeling!", "Justin Timberlake", 2016],
  ["Shape of You", "Ed Sheeran", 2017],
  ["Despacito", "Luis Fonsi", 2017],
  ["HUMBLE.", "Kendrick Lamar", 2017],
  ["Musik sein", "Wincent Weiss", 2016, 1],
  ["God's Plan", "Drake", 2018],
  ["Shallow", "Lady Gaga", 2018],
  ["Old Town Road", "Lil Nas X", 2019],
  ["bad guy", "Billie Eilish", 2019],
  ["Blinding Lights", "The Weeknd", 2019],
  ["Dance Monkey", "Tones and I", 2019],
  ["Roller", "Apache 207", 2019, 1],
  ["Dynamite", "BTS", 2020],
  ["Watermelon Sugar", "Harry Styles", 2020],
  ["drivers license", "Olivia Rodrigo", 2021],
  ["Levitating", "Dua Lipa", 2020],
  ["Heat Waves", "Glass Animals", 2020],
  ["Stay", "The Kid LAROI", 2021],
  ["As It Was", "Harry Styles", 2022],
  ["Anti-Hero", "Taylor Swift", 2022],
  ["About Damn Time", "Lizzo", 2022],
  ["Wildberry Lillet", "Nina Chuba", 2022, 1],
  ["Flowers", "Miley Cyrus", 2023],
  ["Vampire", "Olivia Rodrigo", 2023],
  ["Lose Control", "Teddy Swims", 2023],
  ["Espresso", "Sabrina Carpenter", 2024],
  ["Beautiful Things", "Benson Boone", 2024],
  ["Fortnight", "Taylor Swift", 2024],
  ["Die with a Smile", "Lady Gaga", 2024],
  ["Can't Help Falling in Love", "Elvis Presley", 1961],
  ["Twist and Shout", "The Beatles", 1963],
  ["Yesterday", "The Beatles", 1965],
  ["Here Comes the Sun", "The Beatles", 1969],
  ["Space Oddity", "David Bowie", 1969],
  ["Bridge Over Troubled Water", "Simon & Garfunkel", 1970],
  ["What's Going On", "Marvin Gaye", 1971],
  ["American Pie", "Don McLean", 1971],
  ["Rocket Man", "Elton John", 1972],
  ["Piano Man", "Billy Joel", 1973],
  ["No Woman, No Cry", "Bob Marley", 1975],
  ["Born to Run", "Bruce Springsteen", 1975],
  ["Go Your Own Way", "Fleetwood Mac", 1977],
  ["Dreams", "Fleetwood Mac", 1977],
  ["We Will Rock You", "Queen", 1977],
  ["Heroes", "David Bowie", 1977],
  ["I Will Survive", "Gloria Gaynor", 1978],
  ["Roxanne", "The Police", 1978],
  ["Daddy Cool", "Boney M.", 1976],
  ["Rasputin", "Boney M.", 1978],
  ["Video Killed the Radio Star", "The Buggles", 1979],
  ["London Calling", "The Clash", 1979],
  ["Über den Wolken", "Reinhard Mey", 1974, 1],
  ["Moskau", "Dschinghis Khan", 1979, 1],
  ["Don't You Want Me", "The Human League", 1981],
  ["Africa", "Toto", 1982],
  ["Eye of the Tiger", "Survivor", 1982],
  ["Come On Eileen", "Dexys Midnight Runners", 1982],
  ["Thriller", "Michael Jackson", 1982],
  ["Beat It", "Michael Jackson", 1982],
  ["Sweet Dreams (Are Made of This)", "Eurythmics", 1983],
  ["Girls Just Want to Have Fun", "Cyndi Lauper", 1983],
  ["Purple Rain", "Prince", 1984],
  ["Careless Whisper", "George Michael", 1984],
  ["Wake Me Up Before You Go-Go", "Wham!", 1984],
  ["Shout", "Tears for Fears", 1984],
  ["Everybody Wants to Rule the World", "Tears for Fears", 1985],
  ["Running Up That Hill", "Kate Bush", 1985],
  ["Kiss", "Prince", 1986],
  ["Walk This Way", "Run-D.M.C.", 1986],
  ["Faith", "George Michael", 1987],
  ["Pour Some Sugar on Me", "Def Leppard", 1987],
  ["Where Is My Mind?", "Pixies", 1988],
  ["Free Fallin'", "Tom Petty", 1989],
  ["Love Shack", "The B-52's", 1989],
  ["Der Kommissar", "Falco", 1981, 1],
  ["Jeanny", "Falco", 1985, 1],
  ["Major Tom (Völlig losgelöst)", "Peter Schilling", 1983, 1],
  ["Skandal im Sperrbezirk", "Spider Murphy Gang", 1981, 1],
  ["Irgendwie, irgendwo, irgendwann", "Nena", 1984, 1],
  ["Zu spät", "Die Ärzte", 1988, 1],
  ["Verdamp lang her", "BAP", 1981, 1],
  ["Bochum", "Herbert Grönemeyer", 1984, 1],
  ["Brother Louie", "Modern Talking", 1986, 1],
  ["Enjoy the Silence", "Depeche Mode", 1990],
  ["U Can't Touch This", "MC Hammer", 1990],
  ["Enter Sandman", "Metallica", 1991],
  ["Losing My Religion", "R.E.M.", 1991],
  ["November Rain", "Guns N' Roses", 1992],
  ["Creep", "Radiohead", 1992],
  ["Basket Case", "Green Day", 1994],
  ["Black Hole Sun", "Soundgarden", 1994],
  ["Don't Look Back in Anger", "Oasis", 1996],
  ["Virtual Insanity", "Jamiroquai", 1996],
  ["Torn", "Natalie Imbruglia", 1997],
  ["Around the World", "Daft Punk", 1997],
  ["All Star", "Smash Mouth", 1999],
  ["No Scrubs", "TLC", 1999],
  ["Say My Name", "Destiny's Child", 1999],
  ["Blue (Da Ba Dee)", "Eiffel 65", 1999],
  ["Schrei nach Liebe", "Die Ärzte", 1993, 1],
  ["Männer sind Schweine", "Die Ärzte", 1998, 1],
  ["Alles aus Liebe", "Die Toten Hosen", 1993, 1],
  ["Zehn kleine Jägermeister", "Die Toten Hosen", 1995, 1],
  ["Sie ist weg", "Die Fantastischen Vier", 1995, 1],
  ["MfG", "Die Fantastischen Vier", 1999, 1],
  ["Engel", "Rammstein", 1997, 1],
  ["Verdammt, ich lieb' dich", "Matthias Reim", 1990, 1],
  ["Coco Jamboo", "Mr. President", 1996, 1],
  ["Mambo No. 5", "Lou Bega", 1999, 1],
  ["Anton aus Tirol", "DJ Ötzi", 1999, 1],
  ["Junimond", "Echt", 1999, 1],
  ["Ms. Jackson", "OutKast", 2000],
  ["Beautiful Day", "U2", 2000],
  ["One More Time", "Daft Punk", 2000],
  ["Clint Eastwood", "Gorillaz", 2001],
  ["In the End", "Linkin Park", 2001],
  ["How You Remind Me", "Nickelback", 2001],
  ["Complicated", "Avril Lavigne", 2002],
  ["Without Me", "Eminem", 2002],
  ["Seven Nation Army", "The White Stripes", 2003],
  ["Mr. Brightside", "The Killers", 2004],
  ["Since U Been Gone", "Kelly Clarkson", 2004],
  ["Dragostea Din Tei", "O-Zone", 2003],
  ["Stronger", "Kanye West", 2007],
  ["Single Ladies", "Beyoncé", 2008],
  ["Halo", "Beyoncé", 2008],
  ["Just Dance", "Lady Gaga", 2008],
  ["Use Somebody", "Kings of Leon", 2008],
  ["Empire State of Mind", "Jay-Z", 2009],
  ["Love Story", "Taylor Swift", 2008],
  ["You Belong with Me", "Taylor Swift", 2008],
  ["Party in the U.S.A.", "Miley Cyrus", 2009],
  ["Sonne", "Rammstein", 2001, 1],
  ["Amerika", "Rammstein", 2004, 1],
  ["Ein Kompliment", "Sportfreunde Stiller", 2004, 1],
  ["Mein Block", "Sido", 2004, 1],
  ["Mensch", "Herbert Grönemeyer", 2002, 1],
  ["Dickes B", "Seeed", 2001, 1],
  ["Augenbling", "Seeed", 2006, 1],
  ["Schwarz zu blau", "Peter Fox", 2008, 1],
  ["Alles neu", "Peter Fox", 2008, 1],
  ["Liebe ist alles", "Rosenstolz", 2004, 1],
  ["Ein Stern (...der deinen Namen trägt)", "DJ Ötzi", 2007, 1],
  ["Need You Now", "Lady A", 2010],
  ["Firework", "Katy Perry", 2010],
  ["Teenage Dream", "Katy Perry", 2010],
  ["Only Girl (In the World)", "Rihanna", 2010],
  ["We Found Love", "Rihanna", 2011],
  ["Born This Way", "Lady Gaga", 2011],
  ["Pumped Up Kicks", "Foster the People", 2010],
  ["Rolling in the Deep", "Adele", 2010],
  ["Someone Like You", "Adele", 2011],
  ["Levels", "Avicii", 2011],
  ["Titanium", "David Guetta", 2011],
  ["Sexy and I Know It", "LMFAO", 2011],
  ["Thrift Shop", "Macklemore", 2012],
  ["Radioactive", "Imagine Dragons", 2012],
  ["Royals", "Lorde", 2013],
  ["Wake Me Up", "Avicii", 2013],
  ["Let Her Go", "Passenger", 2012],
  ["Take Me to Church", "Hozier", 2013],
  ["Thinking Out Loud", "Ed Sheeran", 2014],
  ["Photograph", "Ed Sheeran", 2014],
  ["Blank Space", "Taylor Swift", 2014],
  ["Style", "Taylor Swift", 2014],
  ["Hotline Bling", "Drake", 2015],
  ["Can't Feel My Face", "The Weeknd", 2015],
  ["Alright", "Kendrick Lamar", 2015],
  ["Hello", "Adele", 2015],
  ["Stitches", "Shawn Mendes", 2015],
  ["Love Yourself", "Justin Bieber", 2015],
  ["24K Magic", "Bruno Mars", 2016],
  ["Starboy", "The Weeknd", 2016],
  ["Formation", "Beyoncé", 2016],
  ["Cheap Thrills", "Sia", 2016],
  ["Shape of You", "Ed Sheeran", 2017],
  ["Perfect", "Ed Sheeran", 2017],
  ["Sign of the Times", "Harry Styles", 2017],
  ["New Rules", "Dua Lipa", 2017],
  ["Rockstar", "Post Malone", 2017],
  ["God's Plan", "Drake", 2018],
  ["In My Feelings", "Drake", 2018],
  ["Lucid Dreams", "Juice WRLD", 2018],
  ["Sunflower", "Post Malone", 2018],
  ["thank u, next", "Ariana Grande", 2018],
  ["Someone You Loved", "Lewis Capaldi", 2018],
  ["7 rings", "Ariana Grande", 2019],
  ["Señorita", "Shawn Mendes", 2019],
  ["Circles", "Post Malone", 2019],
  ["Don't Start Now", "Dua Lipa", 2019],
  ["Cruel Summer", "Taylor Swift", 2019],
  ["Adore You", "Harry Styles", 2019],
  ["Tage wie diese", "Die Toten Hosen", 2012, 1],
  ["Ding", "Seeed", 2012, 1],
  ["Lila Wolken", "Marteria", 2012, 1],
  ["Einmal um die Welt", "Cro", 2012, 1],
  ["Barfuß am Klavier", "AnnenMayKantereit", 2013, 1],
  ["Traum", "Cro", 2014, 1],
  ["Astronaut", "Sido", 2015, 1],
  ["Oft gefragt", "AnnenMayKantereit", 2016, 1],
  ["Palmen aus Plastik", "Bonez MC", 2016, 1],
  ["Ohne mein Team", "Bonez MC", 2016, 1],
  ["Pocahontas", "AnnenMayKantereit", 2018, 1],
  ["500 PS", "Bonez MC", 2018, 1],
  ["Vermissen", "Juju", 2019, 1],
  ["Save Your Tears", "The Weeknd", 2020],
  ["positions", "Ariana Grande", 2020],
  ["Cardigan", "Taylor Swift", 2020],
  ["Peaches", "Justin Bieber", 2021],
  ["good 4 u", "Olivia Rodrigo", 2021],
  ["MONTERO (Call Me By Your Name)", "Lil Nas X", 2021],
  ["Industry Baby", "Lil Nas X", 2021],
  ["Bad Habits", "Ed Sheeran", 2021],
  ["Stay", "The Kid LAROI", 2021],
  ["Heat Waves", "Glass Animals", 2020],
  ["Unholy", "Sam Smith", 2022],
  ["I'm Good (Blue)", "David Guetta", 2022],
  ["Calm Down", "Rema", 2022],
  ["Stick Season", "Noah Kahan", 2022],
  ["Paint The Town Red", "Doja Cat", 2023],
  ["Greedy", "Tate McRae", 2023],
  ["Lovin On Me", "Jack Harlow", 2023],
  ["Pink Pony Club", "Chappell Roan", 2023],
  ["Birds of a Feather", "Billie Eilish", 2024],
  ["Not Like Us", "Kendrick Lamar", 2024],
  ["APT.", "ROSÉ", 2024],
  ["Good Luck, Babe!", "Chappell Roan", 2024],
  ["Please Please Please", "Sabrina Carpenter", 2024],
  ["Too Sweet", "Hozier", 2024],
  ["Aurelia", "Apache 207", 2020, 1],
  ["Airwaves", "Pashanim", 2020, 1],
  ["Komet", "Udo Lindenberg", 2023, 1],
  ["Friesenjung", "Ski Aggu", 2023, 1],
  ["Bauch Beine Po", "Shirin David", 2024, 1],
  ["Fühlst du das auch", "Ayliva", 2023, 1],
  ["Ich hass dich", "Nina Chuba", 2022, 1],
  ["End of Beginning", "Djo", 2022],
  ["A Bar Song (Tipsy)", "Shaboozey", 2024],
  ["Million Dollar Baby", "Tommy Richman", 2024],
  ["Water", "Tyla", 2023],
  ["Belong Together", "Mark Ambor", 2024],
  ["Stargazing", "Myles Smith", 2024],
  ["Austin", "Dasha", 2023],
  ["I Had Some Help", "Post Malone", 2024],
  ["Texas Hold 'Em", "Beyoncé", 2024],
  ["Slow It Down", "Benson Boone", 2024],
  ["Taste", "Sabrina Carpenter", 2024],
  ["That's So True", "Gracie Abrams", 2024],
  ["Ordinary", "Alex Warren", 2024],
  ["Messy", "Lola Young", 2024],
  ["Sports Car", "Tate McRae", 2025],
  ["Luther", "Kendrick Lamar", 2024],
  ["Timeless", "The Weeknd", 2024],
  ["Abracadabra", "Lady Gaga", 2025],
  ["Back to Friends", "sombr", 2024],
  ["Apple", "Charli XCX", 2024],
  ["Diet Pepsi", "Addison Rae", 2024],
  ["Sailor Song", "Gigi Perez", 2024],
  ["Anxiety", "Doechii", 2024],
  ["Manchild", "Sabrina Carpenter", 2025],
  ["tv off", "Kendrick Lamar", 2024],
  ["SICKO MODE", "Travis Scott", 2018],
  ["The Box", "Roddy Ricch", 2019],
  ["First Class", "Jack Harlow", 2022],
];

function slug(title: string, artist: string, year: number) {
  return `${artist}-${title}-${year}`
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const seen = new Set<string>();

export const CATALOG: CatalogSong[] = ROWS.flatMap(([title, artist, year, german]) => {
  const id = slug(title, artist, year);
  if (seen.has(id)) return [];
  seen.add(id);
  return [{ id, title, artist, year, german: german === 1 }];
});

let titlePool: string[] | null = null;
let artistPool: string[] | null = null;

export function catalogTitles() {
  titlePool ??= [...new Set(CATALOG.map((song) => song.title))];
  return titlePool;
}

export function catalogArtists() {
  artistPool ??= [...new Set(CATALOG.map((song) => song.artist))];
  return artistPool;
}

export function songId(title: string, artist: string, year: number) {
  return slug(title, artist, year);
}

export function matchCatalogSong(title: string, artist: string): CatalogSong | undefined {
  return CATALOG.find(
    (song) =>
      guessMatches(title, song.title, "title") &&
      guessMatches(artist, song.artist, "artist"),
  );
}

export function songsForEra(era: EraId): CatalogSong[] {
  return CATALOG.filter((song) => {
    if (era === "all" || era === "playlist" || era === "mix") return true;
    if (era === "german") return Boolean(song.german);
    if (era === "classic") return song.year <= 1979;
    if (era === "eighties") return song.year >= 1980 && song.year <= 1989;
    if (era === "nineties") return song.year >= 1990 && song.year <= 1999;
    if (era === "two-thousands") return song.year >= 2000 && song.year <= 2009;
    if (era === "tens") return song.year >= 2010 && song.year <= 2019;
    if (era === "today") return song.year >= 2020;
    return true;
  });
}
