import type { CatalogSong, EraId } from "./types";

type Row = [title: string, artist: string, year: number, german?: 1];

const ROWS: Row[] = [
  ["Rock Around the Clock", "Bill Haley & His Comets", 1954],
  ["Hound Dog", "Elvis Presley", 1956],
  ["Jailhouse Rock", "Elvis Presley", 1957],
  ["Johnny B. Goode", "Chuck Berry", 1958],
  ["What'd I Say", "Ray Charles", 1959],
  ["The Twist", "Chubby Checker", 1960],
  ["Stand by Me", "Ben E. King", 1961],
  ["I Want to Hold Your Hand", "The Beatles", 1963],
  ["She Loves You", "The Beatles", 1963],
  ["(I Can't Get No) Satisfaction", "The Rolling Stones", 1965],
  ["Help!", "The Beatles", 1965],
  ["My Generation", "The Who", 1965],
  ["Good Vibrations", "The Beach Boys", 1966],
  ["Paint It, Black", "The Rolling Stones", 1966],
  ["Respect", "Aretha Franklin", 1967],
  ["Light My Fire", "The Doors", 1967],
  ["A Whiter Shade of Pale", "Procol Harum", 1967],
  ["Hey Jude", "The Beatles", 1968],
  ["All Along the Watchtower", "Jimi Hendrix", 1968],
  ["I Heard It Through the Grapevine", "Marvin Gaye", 1968],
  ["Whole Lotta Love", "Led Zeppelin", 1969],
  ["Come Together", "The Beatles", 1969],
  ["Let It Be", "The Beatles", 1970],
  ["Your Song", "Elton John", 1970],
  ["Imagine", "John Lennon", 1971],
  ["Stairway to Heaven", "Led Zeppelin", 1971],
  ["Superstition", "Stevie Wonder", 1972],
  ["Smoke on the Water", "Deep Purple", 1972],
  ["Angie", "The Rolling Stones", 1973],
  ["Autobahn", "Kraftwerk", 1974, 1],
  ["Bohemian Rhapsody", "Queen", 1975],
  ["Wish You Were Here", "Pink Floyd", 1975],
  ["Dancing Queen", "ABBA", 1976],
  ["Hotel California", "Eagles", 1977],
  ["Stayin' Alive", "Bee Gees", 1977],
  ["We Are the Champions", "Queen", 1977],
  ["Y.M.C.A.", "Village People", 1978],
  ["Heart of Glass", "Blondie", 1978],
  ["Another Brick in the Wall, Pt. 2", "Pink Floyd", 1979],
  ["Don't Stop Believin'", "Journey", 1981],
  ["In the Air Tonight", "Phil Collins", 1981],
  ["Tainted Love", "Soft Cell", 1981],
  ["Da Da Da", "Trio", 1982, 1],
  ["Billie Jean", "Michael Jackson", 1983],
  ["Every Breath You Take", "The Police", 1983],
  ["99 Luftballons", "Nena", 1983, 1],
  ["Sonderzug nach Pankow", "Udo Lindenberg", 1983, 1],
  ["Relax", "Frankie Goes to Hollywood", 1983],
  ["Like a Virgin", "Madonna", 1984],
  ["When Doves Cry", "Prince", 1984],
  ["Forever Young", "Alphaville", 1984, 1],
  ["Männer", "Herbert Grönemeyer", 1984, 1],
  ["Take On Me", "a-ha", 1985],
  ["Rock Me Amadeus", "Falco", 1985, 1],
  ["You're My Heart, You're My Soul", "Modern Talking", 1985, 1],
  ["Summer of '69", "Bryan Adams", 1985],
  ["Livin' on a Prayer", "Bon Jovi", 1986],
  ["The Final Countdown", "Europe", 1986],
  ["Walk Like an Egyptian", "The Bangles", 1986],
  ["Sweet Child o' Mine", "Guns N' Roses", 1987],
  ["I Wanna Dance with Somebody", "Whitney Houston", 1987],
  ["Never Gonna Give You Up", "Rick Astley", 1987],
  ["Freiheit", "Westernhagen", 1987, 1],
  ["With or Without You", "U2", 1987],
  ["Fast Car", "Tracy Chapman", 1988],
  ["Hier kommt Alex", "Die Toten Hosen", 1988, 1],
  ["Like a Prayer", "Madonna", 1989],
  ["Wind of Change", "Scorpions", 1990, 1],
  ["Nothing Compares 2 U", "Sinéad O'Connor", 1990],
  ["The Power", "Snap!", 1990, 1],
  ["Smells Like Teen Spirit", "Nirvana", 1991],
  ["Black or White", "Michael Jackson", 1991],
  ["I Will Always Love You", "Whitney Houston", 1992],
  ["Under the Bridge", "Red Hot Chili Peppers", 1992],
  ["Killing in the Name", "Rage Against the Machine", 1992],
  ["What's Up?", "4 Non Blondes", 1993],
  ["Mr. Vain", "Culture Beat", 1993, 1],
  ["Die da!?", "Die Fantastischen Vier", 1993, 1],
  ["Linger", "The Cranberries", 1993],
  ["Zombie", "The Cranberries", 1994],
  ["Wonderwall", "Oasis", 1995],
  ["Gangsta's Paradise", "Coolio", 1995],
  ["You Oughta Know", "Alanis Morissette", 1995],
  ["Abenteuerland", "Pur", 1995, 1],
  ["Wannabe", "Spice Girls", 1996],
  ["Macarena", "Los Del Rio", 1996],
  ["Bitter Sweet Symphony", "The Verve", 1997],
  ["MMMBop", "Hanson", 1997],
  ["Du Hast", "Rammstein", 1997, 1],
  ["Believe", "Cher", 1998],
  ["...Baby One More Time", "Britney Spears", 1998],
  ["How Much Is the Fish?", "Scooter", 1998, 1],
  ["My Heart Will Go On", "Celine Dion", 1998],
  ["Californication", "Red Hot Chili Peppers", 1999],
  ["I Want It That Way", "Backstreet Boys", 1999],
  ["Smooth", "Santana", 1999],
  ["The Real Slim Shady", "Eminem", 2000],
  ["Yellow", "Coldplay", 2000],
  ["Bye Bye Bye", "NSYNC", 2000],
  ["Daylight in Your Eyes", "No Angels", 2001, 1],
  ["Fallin'", "Alicia Keys", 2001],
  ["Can't Get You Out of My Head", "Kylie Minogue", 2001],
  ["Whenever, Wherever", "Shakira", 2001],
  ["Lose Yourself", "Eminem", 2002],
  ["The Scientist", "Coldplay", 2002],
  ["A Thousand Miles", "Vanessa Carlton", 2002],
  ["Hey Ya!", "OutKast", 2003],
  ["Crazy in Love", "Beyoncé", 2003],
  ["In da Club", "50 Cent", 2003],
  ["Yeah!", "Usher", 2004],
  ["This Love", "Maroon 5", 2004],
  ["Perfekte Welle", "Juli", 2004, 1],
  ["Boulevard of Broken Dreams",  "Green Day", 2004],
  ["Feel Good Inc.", "Gorillaz", 2005],
  ["You're Beautiful", "James Blunt", 2005],
  ["Gold Digger", "Kanye West", 2005],
  ["Durch den Monsun", "Tokio Hotel", 2005, 1],
  ["Nur ein Wort", "Wir sind Helden", 2005, 1],
  ["Crazy", "Gnarls Barkley", 2006],
  ["Hips Don't Lie", "Shakira", 2006],
  ["Das Beste", "Silbermond", 2006, 1],
  ["Umbrella", "Rihanna", 2007],
  ["Rehab", "Amy Winehouse", 2007],
  ["Hamma!", "Culcha Candela", 2007, 1],
  ["Vom selben Stern", "Ich + Ich", 2007, 1],
  ["Viva la Vida", "Coldplay", 2008],
  ["Poker Face", "Lady Gaga", 2008],
  ["I Kissed a Girl", "Katy Perry", 2008],
  ["Haus am See", "Peter Fox", 2008, 1],
  ["I Gotta Feeling", "The Black Eyed Peas", 2009],
  ["Bad Romance", "Lady Gaga", 2009],
  ["Use Somebody", "Kings of Leon", 2008],
  ["Rolling in the Deep", "Adele", 2010],
  ["Satellite", "Lena", 2010, 1],
  ["Geboren um zu leben", "Unheilig", 2010, 1],
  ["Just the Way You Are", "Bruno Mars", 2010],
  ["Party Rock Anthem", "LMFAO", 2011],
  ["Somebody That I Used to Know", "Gotye", 2011],
  ["Rolling in the Deep", "Adele", 2010],
  ["Easy", "Cro", 2011, 1],
  ["Call Me Maybe", "Carly Rae Jepsen", 2011],
  ["We Are Young", "fun.", 2011],
  ["Gangnam Style", "PSY", 2012],
  ["Somebody That I Used to Know", "Gotye", 2011],
  ["Diamonds", "Rihanna", 2012],
  ["Locked Out of Heaven", "Bruno Mars", 2012],
  ["Get Lucky", "Daft Punk", 2013],
  ["Happy", "Pharrell Williams", 2013],
  ["Stolen Dance", "Milky Chance", 2013, 1],
  ["Atemlos durch die Nacht", "Helene Fischer", 2013, 1],
  ["Willst du", "Alligatoah", 2013, 1],
  ["All of Me", "John Legend", 2013],
  ["Uptown Funk", "Mark Ronson", 2014],
  ["Shake It Off", "Taylor Swift", 2014],
  ["Auf uns", "Andreas Bourani", 2014, 1],
  ["Chandelier", "Sia", 2014],
  ["Hello", "Adele", 2015],
  ["Sorry", "Justin Bieber", 2015],
  ["See You Again", "Wiz Khalifa", 2015],
  ["Lieblingsmensch", "Namika", 2015, 1],
  ["Chöre", "Mark Forster", 2015, 1],
  ["One Dance", "Drake", 2016],
  ["Cheap Thrills", "Sia", 2016],
  ["Can't Stop the Feeling!", "Justin Timberlake", 2016],
  ["Shape of You", "Ed Sheeran", 2017],
  ["Despacito", "Luis Fonsi", 2017],
  ["HUMBLE.", "Kendrick Lamar", 2017],
  ["Musik sein", "Wincent Weiss", 2016, 1],
  ["God's Plan", "Drake", 2018],
  ["Shallow", "Lady Gaga", 2018],
  ["Old Town Road", "Lil Nas X", 2019],
  ["bad guy", "Billie Eilish", 2019],
  ["Blinding Lights", "The Weeknd", 2019],
  ["Dance Monkey", "Tones and I", 2019],
  ["Roller", "Apache 207", 2019, 1],
  ["Dynamite", "BTS", 2020],
  ["Watermelon Sugar", "Harry Styles", 2020],
  ["drivers license", "Olivia Rodrigo", 2021],
  ["Levitating", "Dua Lipa", 2020],
  ["Heat Waves", "Glass Animals", 2020],
  ["Stay", "The Kid LAROI", 2021],
  ["As It Was", "Harry Styles", 2022],
  ["Anti-Hero", "Taylor Swift", 2022],
  ["About Damn Time", "Lizzo", 2022],
  ["Wildberry Lillet", "Nina Chuba", 2022, 1],
  ["Flowers", "Miley Cyrus", 2023],
  ["Vampire", "Olivia Rodrigo", 2023],
  ["Lose Control", "Teddy Swims", 2023],
  ["Espresso", "Sabrina Carpenter", 2024],
  ["Beautiful Things", "Benson Boone", 2024],
  ["Fortnight", "Taylor Swift", 2024],
  ["Die with a Smile", "Lady Gaga", 2024],
];

function slug(title: string, artist: string, year: number) {
  return `${artist}-${title}-${year}`
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const seen = new Set<string>();

export const CATALOG: CatalogSong[] = ROWS.flatMap(([title, artist, year, german]) => {
  const id = slug(title, artist, year);
  if (seen.has(id)) return [];
  seen.add(id);
  return [{ id, title, artist, year, german: german === 1 }];
});

export function songsForEra(era: EraId): CatalogSong[] {
  return CATALOG.filter((song) => {
    if (era === "all") return true;
    if (era === "german") return Boolean(song.german);
    if (era === "classic") return song.year <= 1979;
    if (era === "eighties") return song.year >= 1980 && song.year <= 1989;
    if (era === "nineties") return song.year >= 1990 && song.year <= 1999;
    if (era === "two-thousands") return song.year >= 2000 && song.year <= 2009;
    if (era === "today") return song.year >= 2010;
    return true;
  });
}
