export type GagItem = { id: string; label: string };
export type GagGroup = { id: string; title: string; items: GagItem[] };

export const GAG_GROUPS: GagGroup[] = [
  {
    id: "platte",
    title: "Platte",
    items: [
      { id: "label", label: "Mitte antippen" },
      { id: "vinyl", label: "Siebenmal die Scheibe" },
    ],
  },
  {
    id: "schrift",
    title: "Schrift",
    items: [{ id: "title", label: "Jahrgang fünfmal tippen" }],
  },
  {
    id: "cheat",
    title: "Cheat",
    items: [{ id: "disco", label: "Konami" }],
  },
  {
    id: "papier",
    title: "Papier",
    items: [{ id: "paper", label: "Weiß unterschreiben" }],
  },
  {
    id: "jahre",
    title: "Mix-Jahre",
    items: [
      { id: "y1969", label: "1969" },
      { id: "y1977", label: "1977" },
      { id: "y1982", label: "1982" },
      { id: "y1984", label: "1984" },
      { id: "y1987", label: "1987" },
      { id: "y1999", label: "1999" },
      { id: "y2000", label: "2000" },
      { id: "y2012", label: "2012" },
    ],
  },
  {
    id: "namen",
    title: "Namen",
    items: [
      { id: "michael-jackson", label: "Michael Jackson" },
      { id: "michael", label: "Michael" },
      { id: "jackson", label: "Jackson" },
      { id: "elvis", label: "Elvis" },
      { id: "madonna", label: "Madonna" },
      { id: "britney", label: "Britney" },
      { id: "adele", label: "Adele" },
      { id: "taylor", label: "Taylor" },
      { id: "eminem", label: "Eminem" },
      { id: "drake", label: "Drake" },
      { id: "beyonce", label: "Beyoncé" },
      { id: "gaga", label: "Gaga" },
      { id: "rihanna", label: "Rihanna" },
      { id: "prince", label: "Prince" },
      { id: "freddie", label: "Freddie" },
      { id: "weeknd", label: "The Weeknd" },
      { id: "kanye", label: "Kanye" },
      { id: "snoop", label: "Snoop" },
      { id: "shakira", label: "Shakira" },
      { id: "ed", label: "Ed Sheeran" },
      { id: "harry", label: "Harry" },
      { id: "beatles", label: "Beatles" },
      { id: "abba", label: "ABBA" },
      { id: "queen", label: "Queen" },
      { id: "oasis", label: "Oasis" },
      { id: "nirvana", label: "Nirvana" },
      { id: "bonjovi", label: "Bon Jovi" },
      { id: "linkin", label: "Linkin Park" },
      { id: "nena", label: "Nena" },
      { id: "falco", label: "Falco" },
      { id: "helene", label: "Helene" },
      { id: "rammstein", label: "Rammstein" },
      { id: "scooter", label: "Scooter" },
      { id: "aerzte", label: "Die Ärzte" },
      { id: "hosen", label: "Toten Hosen" },
      { id: "sido", label: "Sido" },
      { id: "apache", label: "Apache" },
      { id: "fox", label: "Peter Fox" },
      { id: "seeed", label: "Seeed" },
      { id: "cro", label: "Cro" },
      { id: "rick", label: "Rick" },
      { id: "hitster", label: "Hitster" },
      { id: "onkelamoG", label: "onkelamoG" },
      { id: "jahrgang", label: "Jahrgang" },
      { id: "linopix", label: "Linopix" },
      { id: "dj", label: "DJ" },
      { id: "admin", label: "Admin" },
      { id: "host", label: "Host" },
      { id: "alexa", label: "Alexa" },
      { id: "alex", label: "Alex" },
      { id: "sam", label: "Sam" },
      { id: "kim", label: "Kim" },
      { id: "nicki", label: "Nicki" },
    ],
  },
  {
    id: "codes",
    title: "Raumcodes",
    items: [
      { id: "c-abba", label: "ABBA" },
      { id: "c-beef", label: "BEEF" },
      { id: "c-love", label: "LOVE" },
      { id: "c-yeah", label: "YEAH" },
      { id: "c-rock", label: "ROCK" },
      { id: "c-disc", label: "DISC" },
      { id: "c-year", label: "YEAR" },
      { id: "c-1984", label: "1984" },
      { id: "c-2000", label: "2000" },
      { id: "c-gaga", label: "GAGA" },
      { id: "c-rick", label: "RICK" },
      { id: "c-nena", label: "NENA" },
      { id: "c-baby", label: "BABY" },
      { id: "c-king", label: "KING" },
      { id: "c-beat", label: "BEAT" },
    ],
  },
  {
    id: "packs",
    title: "Packs",
    items: [
      { id: "p-party", label: "Party" },
      { id: "p-classic", label: "Classic" },
      { id: "p-80", label: "80er" },
      { id: "p-90", label: "90er" },
      { id: "p-mix", label: "Mix" },
      { id: "p-list", label: "Playlist" },
    ],
  },
  {
    id: "modi",
    title: "Modi",
    items: [
      { id: "v-wild", label: "Verrückter" },
      { id: "v-custom", label: "Custom" },
      { id: "v-blind", label: "Blind" },
      { id: "v-hook", label: "Titel" },
    ],
  },
  {
    id: "chat",
    title: "Chat",
    items: [{ id: "schweinebein", label: "Schweinebein" }],
  },
];

export const GAG_ITEM_TOTAL = GAG_GROUPS.reduce((n, g) => n + g.items.length, 0);

export const GAG_CLIPS: Record<string, { title: string; artist: string; year: number }> = {
  rick: { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  "c-rick": { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  y1987: { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  "michael-jackson": { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
  jackson: { title: "Thriller", artist: "Michael Jackson", year: 1982 },
  y1982: { title: "Thriller", artist: "Michael Jackson", year: 1982 },
  elvis: { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
  "c-king": { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
  y1977: { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  disco: { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  y1969: { title: "Space Oddity", artist: "David Bowie", year: 1969 },
  y1999: { title: "1999", artist: "Prince", year: 1982 },
  prince: { title: "Purple Rain", artist: "Prince", year: 1984 },
  abba: { title: "Dancing Queen", artist: "ABBA", year: 1976 },
  "c-abba": { title: "Dancing Queen", artist: "ABBA", year: 1976 },
  nena: { title: "99 Luftballons", artist: "Nena", year: 1983 },
  "c-nena": { title: "99 Luftballons", artist: "Nena", year: 1983 },
  beatles: { title: "Hey Jude", artist: "The Beatles", year: 1968 },
  "c-love": { title: "All You Need Is Love", artist: "The Beatles", year: 1967 },
  queen: { title: "Don't Stop Me Now", artist: "Queen", year: 1979 },
  "c-rock": { title: "We Will Rock You", artist: "Queen", year: 1977 },
  britney: { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  "c-baby": { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  gaga: { title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  "c-gaga": { title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  falco: { title: "Rock Me Amadeus", artist: "Falco", year: 1985 },
  scooter: { title: "How Much Is the Fish?", artist: "Scooter", year: 1998 },
  rammstein: { title: "Du Hast", artist: "Rammstein", year: 1997 },
};
