/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HinweiseRouteImport } from './routes/hinweise'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as RanglisteRouteImport } from './routes/rangliste'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiScoresRouteImport } from './routes/api/scores'
import { Route as ApiSpotifyRouteImport } from './routes/api/spotify'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api/spotify.callback'
import { Route as ApiSpotifyLoginRouteImport } from './routes/api/spotify.login'
import { Route as ApiSpotifyTokenRouteImport } from './routes/api/spotify.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HinweiseRoute = HinweiseRouteImport.update({
  id: '/hinweise',
  path: '/hinweise',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const RanglisteRoute = RanglisteRouteImport.update({
  id: '/rangliste',
  path: '/rangliste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoresRoute = ApiScoresRouteImport.update({
  id: '/api/scores',
  path: '/api/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyRoute = ApiSpotifyRouteImport.update({
  id: '/api/spotify',
  path: '/api/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiSpotifyRoute,
} as any)
const ApiSpotifyLoginRoute = ApiSpotifyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ApiSpotifyRoute,
} as any)
const ApiSpotifyTokenRoute = ApiSpotifyTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => ApiSpotifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hinweise': typeof HinweiseRoute
  '/konto': typeof KontoRoute
  '/rangliste': typeof RanglisteRoute
  '/api/account': typeof ApiAccountRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/spotify': typeof ApiSpotifyRouteWithChildren
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
  '/api/spotify/token': typeof ApiSpotifyTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hinweise': typeof HinweiseRoute
  '/konto': typeof KontoRoute
  '/rangliste': typeof RanglisteRoute
  '/api/account': typeof ApiAccountRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/spotify': typeof ApiSpotifyRouteWithChildren
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
  '/api/spotify/token': typeof ApiSpotifyTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hinweise': typeof HinweiseRoute
  '/konto': typeof KontoRoute
  '/rangliste': typeof RanglisteRoute
  '/api/account': typeof ApiAccountRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/scores': typeof ApiScoresRoute
  '/api/spotify': typeof ApiSpotifyRouteWithChildren
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
  '/api/spotify/token': typeof ApiSpotifyTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hinweise'
    | '/konto'
    | '/rangliste'
    | '/api/account'
    | '/api/rtc'
    | '/api/scores'
    | '/api/spotify'
    | '/api/spotify/callback'
    | '/api/spotify/login'
    | '/api/spotify/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hinweise'
    | '/konto'
    | '/rangliste'
    | '/api/account'
    | '/api/rtc'
    | '/api/scores'
    | '/api/spotify'
    | '/api/spotify/callback'
    | '/api/spotify/login'
    | '/api/spotify/token'
  id:
    | '__root__'
    | '/'
    | '/hinweise'
    | '/konto'
    | '/rangliste'
    | '/api/account'
    | '/api/rtc'
    | '/api/scores'
    | '/api/spotify'
    | '/api/spotify/callback'
    | '/api/spotify/login'
    | '/api/spotify/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HinweiseRoute: typeof HinweiseRoute
  KontoRoute: typeof KontoRoute
  RanglisteRoute: typeof RanglisteRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiScoresRoute: typeof ApiScoresRoute
  ApiSpotifyRoute: typeof ApiSpotifyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinweise': {
      id: '/hinweise'
      path: '/hinweise'
      fullPath: '/hinweise'
      preLoaderRoute: typeof HinweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rangliste': {
      id: '/rangliste'
      path: '/rangliste'
      fullPath: '/rangliste'
      preLoaderRoute: typeof RanglisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scores': {
      id: '/api/scores'
      path: '/api/scores'
      fullPath: '/api/scores'
      preLoaderRoute: typeof ApiScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify': {
      id: '/api/spotify'
      path: '/api/spotify'
      fullPath: '/api/spotify'
      preLoaderRoute: typeof ApiSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/callback': {
      id: '/api/spotify/callback'
      path: '/callback'
      fullPath: '/api/spotify/callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof ApiSpotifyRoute
    }
    '/api/spotify/login': {
      id: '/api/spotify/login'
      path: '/login'
      fullPath: '/api/spotify/login'
      preLoaderRoute: typeof ApiSpotifyLoginRouteImport
      parentRoute: typeof ApiSpotifyRoute
    }
    '/api/spotify/token': {
      id: '/api/spotify/token'
      path: '/token'
      fullPath: '/api/spotify/token'
      preLoaderRoute: typeof ApiSpotifyTokenRouteImport
      parentRoute: typeof ApiSpotifyRoute
    }
  }
}

interface ApiSpotifyRouteChildren {
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
  ApiSpotifyLoginRoute: typeof ApiSpotifyLoginRoute
  ApiSpotifyTokenRoute: typeof ApiSpotifyTokenRoute
}

const ApiSpotifyRouteChildren: ApiSpotifyRouteChildren = {
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
  ApiSpotifyLoginRoute: ApiSpotifyLoginRoute,
  ApiSpotifyTokenRoute: ApiSpotifyTokenRoute,
}

const ApiSpotifyRouteWithChildren = ApiSpotifyRoute._addFileChildren(
  ApiSpotifyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HinweiseRoute: HinweiseRoute,
  KontoRoute: KontoRoute,
  RanglisteRoute: RanglisteRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiScoresRoute: ApiScoresRoute,
  ApiSpotifyRoute: ApiSpotifyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
