/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HinweiseRouteImport } from './routes/hinweise'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as RanglisteRouteImport } from './routes/rangliste'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiScoresRouteImport } from './routes/api/scores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HinweiseRoute = HinweiseRouteImport.update({
  id: '/hinweise',
  path: '/hinweise',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const RanglisteRoute = RanglisteRouteImport.update({
  id: '/rangliste',
  path: '/rangliste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoresRoute = ApiScoresRouteImport.update({
  id: '/api/scores',
  path: '/api/scores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hinweise': typeof HinweiseRoute
  '/konto': typeof KontoRoute
  '/rangliste': typeof RanglisteRoute
  '/api/account': typeof ApiAccountRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/scores': typeof ApiScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hinweise': typeof HinweiseRoute
  '/konto': typeof KontoRoute
  '/rangliste': typeof RanglisteRoute
  '/api/account': typeof ApiAccountRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/scores': typeof ApiScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hinweise': typeof HinweiseRoute
  '/konto': typeof KontoRoute
  '/rangliste': typeof RanglisteRoute
  '/api/account': typeof ApiAccountRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/scores': typeof ApiScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hinweise'
    | '/konto'
    | '/rangliste'
    | '/api/account'
    | '/api/rtc'
    | '/api/scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hinweise'
    | '/konto'
    | '/rangliste'
    | '/api/account'
    | '/api/rtc'
    | '/api/scores'
  id:
    | '__root__'
    | '/'
    | '/hinweise'
    | '/konto'
    | '/rangliste'
    | '/api/account'
    | '/api/rtc'
    | '/api/scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HinweiseRoute: typeof HinweiseRoute
  KontoRoute: typeof KontoRoute
  RanglisteRoute: typeof RanglisteRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiScoresRoute: typeof ApiScoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinweise': {
      id: '/hinweise'
      path: '/hinweise'
      fullPath: '/hinweise'
      preLoaderRoute: typeof HinweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rangliste': {
      id: '/rangliste'
      path: '/rangliste'
      fullPath: '/rangliste'
      preLoaderRoute: typeof RanglisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scores': {
      id: '/api/scores'
      path: '/api/scores'
      fullPath: '/api/scores'
      preLoaderRoute: typeof ApiScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HinweiseRoute: HinweiseRoute,
  KontoRoute: KontoRoute,
  RanglisteRoute: RanglisteRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiScoresRoute: ApiScoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
